import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import { FitnessPlanProvider } from "@/context/fitnessplancontext";
import ToastProvider from "@/components/toastprovider";
// import { FitnessProvider } from "@/context/fitness-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "my fit log app",
  description: "Generated by create next app",
};

 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <FitnessPlanProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastProvider/>
        </FitnessPlanProvider>
      </body>
    </html>
  );
}